{% set version = "0.15.0" %}

package:
  name: biggus
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/SciTools/biggus/archive/v{{ version }}.tar.gz
  sha256: 81481f3b3632b7e99fae58c6034c6b351560ceff976ce4860d5c3b2f68713dc7

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - six

test:
  imports:
    - biggus

about:
  home: https://pypi.python.org/pypi/Biggus
  license: LGPL-3.0
  license_file: COPYING.LESSER
  summary: 'Virtual large arrays and lazy evaluation.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - marqh
