# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DWhfudxHzs1uhaZTcNGcXuzpmK6X1QYtIOaFyxrys9dPxgYzH+oH5dzN3z2la1OLVknWz+igOtXevh5M7AHoKSW62drfxNfZaq3p8iKC/h0qiITcpe8OCWl574EoPzntdp8NX8QNaqtgeJZq/CRJrpDGjE1g2CV3C/OwsZcB4HX0+Z2MLBo5yleDXBiV7Gzfsa8uPPclGy1sRjVFEOAadBV09DHsNEpYhXpzOfAbbWJ5dFRg16OLgIMdpmOLRJ4gXXWjATV4WDN5uosIz2SNChmcjdF6ZE+VnLUN/lB+2DDxEAKkBKHb1SeUT6cdNd5ixPhw4P8CJk/II3VXREZC4PLcdscnHPkqK+nRKhDosdyWdy+nLg1iuTGX1aIYAW5tOYcFY/Pf4Lsmx/kUm9wKccJJkMqlTqwmafDmXrPLK1y2O052WkzkKiNBw968wKipaE3YHsgsBLzizux57HBjzvIlMaGrLmM/DUgVp0dxoj6AB5IHyoSTQoheW9jCPzcBvfOuu+7Re9RxbvcNgvJN3Sx9Fi9wtHMuU1tX3ue0wcuXgIzvqwZPeD0NSyyzVZwVdGP7rpoN2vV2CNfIzzKvqwdwC70O+gcLZuRSCRZ2Win4ouxpAF7UUr86ckJ1sLR1gk4IURa2H6hpeNjMAJFRJ69x91FpelPho9Som1+haVQ="


before_install:
    # Remove homebrew.
    - brew remove --force --ignore-dependencies $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
