travis:
  secure:
    BINSTAR_TOKEN: DWhfudxHzs1uhaZTcNGcXuzpmK6X1QYtIOaFyxrys9dPxgYzH+oH5dzN3z2la1OLVknWz+igOtXevh5M7AHoKSW62drfxNfZaq3p8iKC/h0qiITcpe8OCWl574EoPzntdp8NX8QNaqtgeJZq/CRJrpDGjE1g2CV3C/OwsZcB4HX0+Z2MLBo5yleDXBiV7Gzfsa8uPPclGy1sRjVFEOAadBV09DHsNEpYhXpzOfAbbWJ5dFRg16OLgIMdpmOLRJ4gXXWjATV4WDN5uosIz2SNChmcjdF6ZE+VnLUN/lB+2DDxEAKkBKHb1SeUT6cdNd5ixPhw4P8CJk/II3VXREZC4PLcdscnHPkqK+nRKhDosdyWdy+nLg1iuTGX1aIYAW5tOYcFY/Pf4Lsmx/kUm9wKccJJkMqlTqwmafDmXrPLK1y2O052WkzkKiNBw968wKipaE3YHsgsBLzizux57HBjzvIlMaGrLmM/DUgVp0dxoj6AB5IHyoSTQoheW9jCPzcBvfOuu+7Re9RxbvcNgvJN3Sx9Fi9wtHMuU1tX3ue0wcuXgIzvqwZPeD0NSyyzVZwVdGP7rpoN2vV2CNfIzzKvqwdwC70O+gcLZuRSCRZ2Win4ouxpAF7UUr86ckJ1sLR1gk4IURa2H6hpeNjMAJFRJ69x91FpelPho9Som1+haVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
